apiVersion: apps/v1
kind: Deployment
metadata:
  name: annotation-export
spec:
  replicas: 1
  selector:
    matchLabels:
      run: annotation-export
  template:
    metadata:
      labels:
        run: annotation-export
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: stats-pipeline
        # The exact image to be deployed is replaced by gke-deploy, this is
        # a placeholder.
        image: gcr.io/mlab-sandbox/stats-pipeline
        # NOTE: in "local" output mode, and export "annotation" mode, the
        # stats-pipeline will write results to subdirectories of the named
        # -bucket directory.
        args:
          - -prometheusx.listen-address=:9990
          - -exporter.query-workers=2
          - -config=/etc/annotation-export/config-annotation-export.json
          - -export=annotation
          - -output=local
          - -bucket=/var/spool/ndt/annotation
          - -project=mlab-sandbox
        ports:
          # This is so Prometheus can be scraped.
          - name: prometheus-port
            containerPort: 9990
          - name: pusher-port
            containerPort: 9991
          - name: service-port
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /metrics
            port: prometheus-port
        # Note: This service runs on a dedicated 8-CPU node.
        resources:
          limits:
            cpu: "8"
            memory: "30Gi"
          requests:
            cpu: "0.5"
            memory: "2Gi"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/annotation-export
        - name: shared-export-dir
          mountPath: /var/spool/ndt
      - name: pusher
        image: measurementlab/pusher:v1.20
        args:
          - -prometheusx.listen-address=:9991
          - -bucket=thirdparty-annotation-mlab-sandbox
          - -experiment=ndt
          - -datatype=annotation
          - -directory=/var/spool/ndt
          - -node_name=third-party
          - -archive_size_threshold=5MB
          - -max_file_age=10m               # No need to wait after writing to upload a file (default 1h).
          - -archive_wait_time_min=10m      # (default 30m0s)
          - -archive_wait_time_expected=20m # (default 1h0m0s)
          - -archive_wait_time_max=30m      # (default 2h0m0s)
          - -sigterm_wait_time=60s
          - -metadata=MLAB.server.name=data-processing
          - -metadata=MLAB.experiment.name=ndt
          - -metadata=MLAB.pusher.image=measurementlab/pusher:v1.20
          - -metadata=MLAB.pusher.src.url=https://github.com/m-lab/pusher/tree/v1.20
        volumeMounts:
        - name: shared-export-dir
          mountPath: /var/spool/ndt
      nodeSelector:
        stats-pipeline-node: 'true'
      volumes:
      - name: config-volume
        configMap:
          name: stats-pipeline-config
      - name: shared-export-dir
        emptyDir: {}
